# leno_admin开发环境配置
version: "1"

networks:
  app-leno-admin-web:
    driver: bridge

services:
  mysql:
    image: registry.cn-shenzhen.aliyuncs.com/zwc-docker/leno_admin:mysql-8.0
    ports:
      - 9920:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - app-leno-admin-web
    environment:
      - TZ=Asia/Guangzhou
      - MYSQL_ROOT_PASSWORD=Aa363689;
    volumes:
      - /home/leno_admin/mysql/data:/var/lib/mysql
      - /home/leno_admin/mysql/logs:/logs

  redis:
    image: registry.cn-shenzhen.aliyuncs.com/zwc-docker/leno_admin:redis-1.0
    ports:
      - 9910:6379
    networks:
      - app-leno-admin-web
    environment:
      - TZ=Asia/Guangzhou
      - REDIS_PASSWORD=admin123

  backend:
    image: registry.cn-shenzhen.aliyuncs.com/zwc-docker/leno_admin:lenoAdminDevEnv-1.0
    ports:
      - 9900:9900
    depends_on:
      - mysql
      - redis
    networks:
      - app-leno-admin-web
